export { canonical, roleTable, type CanonicalOptions } from './canonical.js'
export { library, libraryRoleTable, type LibraryOptions } from './library.js'
export { fsd, fsdRoleTable, type FsdOptions } from './fsd.js'
export { designSystem, deps, type DesignSystemOptions, type DepsOptions } from './design-system.js'
export { copy } from './copy.js'
export { i18nextKit, type I18nextKitOptions } from './i18n-kits/i18next.js'
export { noneI18nKit } from './i18n-kits/none.js'
export { metrics, type CoverageOptions, type MetricsOptions, type PerDirMin } from './metrics.js'
export { hygiene } from './hygiene.js'
export { i18n, uiKit } from './kit.js'
export { stack, type StackOptions } from './stack.js'
export { antdKit } from './ui-kits/antd.js'
export { noneKit } from './ui-kits/none.js'

/** 把一个适配器包成预设：`uiKit(antdKit())` */
