export { canonical, roleTable, type CanonicalOptions } from './canonical.js'
export { library, libraryRoleTable, type LibraryOptions } from './library.js'
export { fsd, fsdRoleTable, type FsdOptions } from './fsd.js'
export { designSystem, deps, type DesignSystemOptions, type DepsOptions } from './design-system.js'
export { copy } from './copy.js'
export { i18nextKit, type I18nextKitOptions } from './i18n-kits/i18next.js'
export { axiosKit, AXIOS_APIS } from './http-kits/axios.js'
export { noneHttpKit } from './http-kits/none.js'
export { noneI18nKit } from './i18n-kits/none.js'
export { metrics, type CoverageOptions, type MetricsOptions, type PerDirMin } from './metrics.js'
export { hygiene } from './hygiene.js'
export { dataLayer, http, i18n, router, styles, uiKit } from './kit.js'
export { reactRouterKit } from './router-kits/react-router.js'
export { noneRouterKit } from './router-kits/none.js'
export { reactQueryKit } from './data-layer-kits/react-query.js'
export { noneDataLayerKit } from './data-layer-kits/none.js'
export { analytics } from './analytics.js'
export { errorPolicy, type ErrorPolicyOptions } from './error-policy.js'
export { endpoints, type EndpointsOptions } from './endpoints.js'
export { envReads } from './env-reads.js'
export { callSites } from './call-sites.js'
export { cssModulesKit } from './styles-kits/css-modules.js'
export { noneStylesKit } from './styles-kits/none.js'
export { stack, type StackOptions } from './stack.js'
export { antdKit } from './ui-kits/antd.js'
export { noneKit } from './ui-kits/none.js'

/** 把一个适配器包成预设：`uiKit(antdKit())` */
export { permissions, type PermissionsOptions } from './permissions.js'
